[package]
name = "runec_parse"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
runec_source = { path = "../runec_source" }
runec_errors = { path = "../runec_errors" }
runec_utils = { path = "../runec_utils" }
runec_ast = { path = "../runec_ast" }

[dev-dependencies]
runec_test_utils = { path = "../runec_test_utils" }
