[package]
name = "runec_parse"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
runec_source = { workspace = true }
runec_errors = { workspace = true }
runec_utils = { workspace = true }
runec_ast = { workspace = true }

[dev-dependencies]
runec_test_utils = { workspace = true }
