[package]
name = "runec_codegen_cranelift"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
cranelift-object = { workspace = true }
runec_abi = { workspace = true }
runec_builtins = { workspace = true }
runec_errors = { workspace = true }
runec_mir = { workspace = true }
runec_source = { workspace = true }
runec_hir = { workspace = true }
runec_utils = { workspace = true }

[dev-dependencies]
