[package]
name = "runec_mir"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
runec_abi = { workspace = true }
runec_builtins = { workspace = true }
runec_hir = { workspace = true }
runec_semantic = { workspace = true }
runec_source = { workspace = true }
runec_errors = { workspace = true }
runec_utils = { workspace = true }

[dev-dependencies]
runec_ast = { workspace = true }
